name: Update github myprofile

on: 'page_build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.1
      with:
        ref: v2.5.1

    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./github_myprofile_updater
        python3 update.py
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "zhouzenghui.p@qq.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GHRS_GITHUB_API_TOKEN }}@github.com/MaxwelsDonc/MaxwelsDonc.git"
        

        git add README.md
        git add images

        git commit -m "update my description automatically"
        git push "${remote_repo}" HEAD:main --force